.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH REZOSUP-SOLIDIRCD 1 "December 18, 2012"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
ircd \- Rezosup IRCd
.SH SYNOPSIS
.B ircd
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B rezosup-solidircd
command.
.SH OPTIONS
The ircd accepts the following options:
.TP
.B \-f
Read configuration from the given file
.TP
.B \-r
Execute in the given directory (including entropy, pid, ...) files
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.SH AUTHOR
rezosup-solidircd was written by various teams, refer to the Copyright license.
.PP
This manual page was written by Raphaël Barrois <xelnor@rezosup.net>,
for the Debian project (and may be used by others).
